version: "3"
services:

  client:
    build: ./client
    image: product-fetcher-generator-client:1.0.0
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    environment:
      - HONEY_NPM_TOKEN

  server:
    build: ./server
    image: product-fetcher-generator-server:1.0.0
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - HONEY_NPM_TOKEN
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7.23
    container_name: mysql57
    restart: always
    environment:
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_DATABASE: vim_generator
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql:/var/lib/mysql
