version: "3"
services:

  client:
    build: ./client
    image: product-fetcher-generator-client:1.0.0
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    environment:
      - HONEY_NPM_TOKEN

  server:
    build: ./server
    image: product-fetcher-generator-server:1.0.0
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    environment:
      - HONEY_NPM_TOKEN
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - prisma
      - mysql

  prisma:
    image: prismagraphql/prisma:1.19
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
            migrations: true

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
