import Freezer from 'freezer-js';

const defaults = {
  store: {
    storeId: '',
    productPageUrl: '',
  },
  productObservation: {
    schemaVersion: '4.0.0',
    vimVersion: '1.0.0',
    variantId: '',
    parentId: '',
    title: '',
    brand: '',
    description: '',
    extDescription: '',
    priceCurrent: '',
    priceList: '',
    currency: '',
    canonicalUrl: '',
    isCanonical: false,
    upc: '',
    keywords: [],
    categories: [],
    productStates: [],
    productDetails: {},
    storeExtraInfo: {},
    similarProducts: [],
    relatedProducts: [],
    imageUrlPrimary: '',
    imageUrlSecondaries: [],
    ratingCount: '',
    ratingValue: '',
    quantityInStock: '',
    quantityRequired: '',
    quantityAllowed: '',
    quantityIncrement: '',
    finalSale: false,
    deals: '',
    inStock: false,
    imprint: false,
  },
  metadata: {},
  ui: {
    activeTab: '1',
    activePane: 'xhr',
    generatedCode: '',
    validationErrors: {},
    productPageUrls: [],
    isAnalyzingProductPage: false,
  },
};

export default new Freezer(defaults);
